import Head from "next/head";
import homeStyles from "@/styles/Home.module.css";
import { GetStaticProps, NextPage } from "next";
import { getSortedPostsData } from "@/lib/posts";
import Link from "next/link";

// 홈페이지 컴포넌트를 정의합니다.
const Home = ({
  allPostsData,
}: {
  allPostsData: {
    date: string;
    title: string;
    id: string;
  }[];
}) => {
  // 홈페이지의 HTML 구조를 반환합니다.
  return (
    <div>
      <Head>
        <title>minsangOh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={homeStyles.headingMd}>
        <p> [minsang Oh Introduction] </p>
        <p>(this is a website)</p>
      </section>

      <section className={`${homeStyles.headingMd} ${homeStyles.padding1px}`}>
        <h2 className={homeStyles.headingLg}>Blog</h2>
        <ul className={homeStyles.list}>
          {allPostsData.map(({ id, date, title }) => (
            <li className={homeStyles.listItem} key={id}>
              <Link href={`/posts/${id}`} legacyBehavior >
                <a>{title}</a>
              </Link>
              <br />
              <small className={homeStyles.lightText}>{date}</small>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
};




// 기본 export로 홈 컴포넌트를 정의합니다.
export default Home;




// 정적 속성을 생성하는 함수입니다.
export const getStaticProps: GetStaticProps = async () => {
  
  // 정렬된 게시글 데이터를 가져옵니다.
  const allPostsData = getSortedPostsData();
  
  // 가져온 데이터를 props로 전달합니다.
  return {
    props: {
      allPostsData,
    },
  };
};
